function out1 = eqFextWz(phi,psi,r0x,r0y,r0z,th)
%EQFEXTWZ
%    OUT1 = EQFEXTWZ(PHI,PSI,R0X,R0Y,R0Z,TH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    04-Jun-2020 11:50:42

t2 = sin(th);
t3 = cos(psi);
t4 = sin(phi);
t5 = cos(phi);
t6 = sin(psi);
t8 = cos(th);
t15 = t4.*t6;
t16 = t2.*t3.*t5;
t17 = t15+t16;
t18 = r0x.*t17;
t19 = t3.*t4;
t20 = t2.*t5.*t6;
t21 = t19-t20;
t22 = r0y.*t21;
t23 = r0z.*t5.*t8;
t24 = t18-t22+t23+1.0./5.0;
t7 = abs(t24);
t26 = t5.*t6;
t27 = t2.*t3.*t4;
t28 = t26-t27;
t29 = r0x.*t28;
t30 = t3.*t5;
t31 = t2.*t4.*t6;
t32 = t30+t31;
t33 = r0y.*t32;
t34 = r0z.*t4.*t8;
t35 = -t29+t33+t34;
t9 = abs(t35);
t11 = r0z.*t2;
t12 = r0x.*t3.*t8;
t13 = r0y.*t6.*t8;
t14 = -t11+t12+t13;
t10 = abs(t14);
t25 = t7.^2;
t36 = t9.^2;
t37 = t10.^2;
t38 = t25+t36+t37;
t39 = t25+t37;
t40 = 1.0./t39;
t41 = pi.*(1.0e2./9.0);
t42 = r0z.*t2.*1i;
t43 = r0x.*t3.*t8.*-1i;
t44 = r0y.*t6.*t8.*-1i;
t45 = t18-t22+t23+t42+t43+t44+1.0./5.0;
t46 = angle(t45);
t47 = t41-t46.*2.0e2;
t48 = sqrt(t38);
t49 = t48.*2.0e3;
t50 = t49-1.2e3;
t51 = 1.0./sqrt(t38);
out1 = t2.*(t24.*t40.*t47+t14.*t50.*t51)+t5.*t8.*(t14.*t40.*t47-t24.*t50.*t51)-t4.*t8.*t35.*t50.*t51;
