# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters

Kd_joint          : [1, 0.2, 0.2]
Kp_joint          : [3, 3, 3]

#Kp_body           : [100, 100, 100]
#Kd_body           : [10, 10, 10]

#Kp_foot           : [500, 500, 500]
#Kd_foot           : [20, 20, 20]

#Kp_ori            : [100, 100, 100]
#Kd_ori            : [10, 10, 10]


#Kd_joint          : [1.5, 1.5, 1.5]
#Kp_joint          : [15, 15, 15]

Kp_body           : [100, 100, 100]
Kd_body           : [10, 10, 10]

Kp_foot           : [3000, 3000, 3000] #[500, 500, 500]
Kd_foot           : [20, 20, 20] #[10, 10, 10]

#Kp_foot           : [200, 200, 200]
#Kd_foot           : [20, 20, 20]

Kp_ori            : [100, 100, 100]
Kd_ori            : [10, 10, 10]

cmpc_gait         : 9
cmpc_bonus_swing  : 0

use_wbc           : 1
xmaxfs            : 0.5
ymaxfs            : 0.5
yawmaxfs          : 1.5
rollmaxfs         : 0
pitchdesin        : 0
Npar1             : 25 #31 #30 #15 16
Npar2             : 6 #8 #2
Npar3             : 4 #9 #3 #3 4
bo_hei_jum        : 0.24
bo_height         : 0.1 #
coef_fil          : 0.4
muest             : 0.45
shiftleg          : 0.0
slidshift         : 0.02
det_terrn         : 0.0 #
ori_pla_body      : 0.0 #
ifleap            : 1.0 #
dxjump            : -0.8 #
dyjump            : 0.0
noncopjump        : 0.0 #
erlylnd           : 1.0
ltelnd            : 1.0
apla2align        : 0.0
jumppg            : 0.0
ywrtjmp           : 0.0
savdat            : 0.0
bckflstab         : 1.0
sideflstab        : 0.0

quasig            : 1
Qwei2             : [2.0, 2.0, 2.0] #w[1.0, 1.0, 1.0]
#40
Qwei3             : [20.0, 20.0, 300.0] #w[10.0, 10.0, 100.0] #leap [100.0, 100.0, 1000.0]
#30.0,30.0,40.0
Qwei4             : [1.0, 1.0, 1.0] #l [10.0, 10.0, 10.0]
#40
Qwei5             : [1.0, 1.0, 1.0]
#40
Qweiu             : [0.0002, 0.0002, 1e-05] #w[6e-05,6e-05,1e-05] #l [0.0001, 0.0001, 0.0001]
#4e-06
stance_legs       : 4

# Gait parameters
gait_type             : 4
gait_period_time      : 0.5
gait_switching_phase  : 0.5
gait_override         : 4
